{% set name = "metadata-inspector" %}
{% set version = "2024.10.15" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/metadata_inspector-{{ version }}.tar.gz
  sha256: a99d6a1dc195a1afe20463f5f98b5fb5831227f182d84156cb48494f68ecc8f1

build:
  entry_points:
    - metadata-inspector = metadata_inspector:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - cftime
    - dask-core
    - h5netcdf
    - hurry.filesize
    - netcdf4
    - numpy >=1.20.3
    - python >=3.7
    - cfgrib
    - requests
    - xarray
    - zarr

test:
  imports:
    - metadata_inspector
  commands:
    - pip check
    - metadata-inspector --help
  requires:
    - pip

about:
  home: https://github.com/FREVA-CLINT/metadata-inspektor.git
  summary: Inspect metadata of weather/climate datasets
  dev_url: https://github.com/FREVA-CLINT/metadata-inspektor
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - antarcticrainforest
